export const externalPathsNPM = {
   '@typhonjs-svelte/lib/action/dom': '@typhonjs-fvtt/svelte/action/dom',
   '@typhonjs-svelte/lib/animate': '@typhonjs-fvtt/svelte/animate',
   '@typhonjs-svelte/lib/animate/action': '@typhonjs-fvtt/svelte/animate/action',
   '@typhonjs-svelte/lib/store/derived': '@typhonjs-fvtt/svelte/store/derived',
   '@typhonjs-svelte/lib/store/dom': '@typhonjs-fvtt/svelte/store/dom',
   '@typhonjs-svelte/lib/store/position': '@typhonjs-fvtt/svelte/store/position',
   '@typhonjs-svelte/lib/store/storage/web': '@typhonjs-fvtt/svelte/store/storage/web',
   '@typhonjs-svelte/lib/store/storage/web/plugin': '@typhonjs-fvtt/svelte/store/storage/web/plugin',
   '@typhonjs-svelte/lib/transition': '@typhonjs-fvtt/svelte/transition',
   '@typhonjs-svelte/lib/util': '@typhonjs-fvtt/svelte/util',

   '@typhonjs-svelte/runtime-base/data/compress': '@typhonjs-svelte/runtime-base/data/compress',
   '@typhonjs-svelte/runtime-base/data/format/base64': '@typhonjs-svelte/runtime-base/data/format/base64',
   '@typhonjs-svelte/runtime-base/data/format/json5': '@typhonjs-svelte/runtime-base/data/format/json5',
   '@typhonjs-svelte/runtime-base/data/format/msgpack': '@typhonjs-svelte/runtime-base/data/format/msgpack',
   '@typhonjs-svelte/runtime-base/data/format/msgpack/compress': '@typhonjs-svelte/runtime-base/data/format/msgpack/compress',
   '@typhonjs-svelte/runtime-base/data/format/unicode': '@typhonjs-svelte/runtime-base/data/format/unicode',
   '@typhonjs-svelte/runtime-base/data/struct/cache/quick-lru': '@typhonjs-svelte/runtime-base/data/struct/cache/quick-lru',
   '@typhonjs-svelte/runtime-base/data/struct/hash/array': '@typhonjs-svelte/runtime-base/data/struct/hash/array',
   '@typhonjs-svelte/runtime-base/data/struct/search/trie': '@typhonjs-svelte/runtime-base/data/struct/search/trie',
   '@typhonjs-svelte/runtime-base/data/struct/search/trie/query': '@typhonjs-svelte/runtime-base/data/struct/search/trie/query',
   '@typhonjs-svelte/runtime-base/data/struct/store/reducer': '@typhonjs-svelte/runtime-base/data/struct/store/reducer',
   '@typhonjs-svelte/runtime-base/data/struct/store/reducer/array-object': '@typhonjs-svelte/runtime-base/data/struct/store/reducer/array-object',
   '@typhonjs-svelte/runtime-base/math/gl-matrix': '@typhonjs-svelte/runtime-base/math/gl-matrix',
   '@typhonjs-svelte/runtime-base/math/interpolate': '@typhonjs-svelte/runtime-base/math/interpolate',
   '@typhonjs-svelte/runtime-base/math/physics': '@typhonjs-svelte/runtime-base/math/physics',
   '@typhonjs-svelte/runtime-base/math/util': '@typhonjs-svelte/runtime-base/math/util',
   '@typhonjs-svelte/runtime-base/plugin/manager': '@typhonjs-svelte/runtime-base/plugin/manager',
   '@typhonjs-svelte/runtime-base/plugin/manager/eventbus': '@typhonjs-svelte/runtime-base/plugin/manager/eventbus',
   '@typhonjs-svelte/runtime-base/plugin/manager/eventbus/buses': '@typhonjs-svelte/runtime-base/plugin/manager/eventbus/buses',
   '@typhonjs-svelte/runtime-base/util': '@typhonjs-svelte/runtime-base/util',
   '@typhonjs-svelte/runtime-base/util/async': '@typhonjs-svelte/runtime-base/util/async',
   '@typhonjs-svelte/runtime-base/util/browser': '@typhonjs-svelte/runtime-base/util/browser',
   '@typhonjs-svelte/runtime-base/util/object': '@typhonjs-svelte/runtime-base/util/object',
   '@typhonjs-svelte/runtime-base/util/store': '@typhonjs-svelte/runtime-base/util/store',

   // Exclude as external, but do not translate module references.
   'svelte': 'svelte',
   'svelte/animate': 'svelte/animate',
   'svelte/easing': 'svelte/easing',
   'svelte/internal': 'svelte/internal',
   'svelte/motion': 'svelte/motion',
   'svelte/store': 'svelte/store',
   'svelte/transition': 'svelte/transition',

   '@typhonjs-fvtt/svelte/action/dom': '@typhonjs-fvtt/svelte/action/dom',
   '@typhonjs-fvtt/svelte/animate': '@typhonjs-fvtt/svelte/animate',
   '@typhonjs-fvtt/svelte/animate/action': '@typhonjs-fvtt/svelte/animate/action',
   '@typhonjs-fvtt/svelte/application': '@typhonjs-fvtt/svelte/application',
   '@typhonjs-fvtt/svelte/application/dialog': '@typhonjs-fvtt/svelte/application/dialog',
   '@typhonjs-fvtt/svelte/application/legacy': '@typhonjs-fvtt/svelte/application/legacy',
   '@typhonjs-fvtt/svelte/component/core': '@typhonjs-fvtt/svelte/component/core',
   '@typhonjs-fvtt/svelte/component/dialog': '@typhonjs-fvtt/svelte/component/dialog',
   '@typhonjs-fvtt/svelte/gsap': '@typhonjs-fvtt/svelte/gsap',
   '@typhonjs-fvtt/svelte/gsap/plugin': '@typhonjs-fvtt/svelte/gsap/plugin',
   '@typhonjs-fvtt/svelte/gsap/plugin/bonus': '@typhonjs-fvtt/svelte/gsap/plugin/bonus',
   '@typhonjs-fvtt/svelte/helper': '@typhonjs-fvtt/svelte/helper',
   '@typhonjs-fvtt/svelte/store/derived': '@typhonjs-fvtt/svelte/store/derived',
   '@typhonjs-fvtt/svelte/store/dom': '@typhonjs-fvtt/svelte/store/dom',
   '@typhonjs-fvtt/svelte/store/fvtt': '@typhonjs-fvtt/svelte/store/fvtt',
   '@typhonjs-fvtt/svelte/store/position': '@typhonjs-fvtt/svelte/store/position',
   '@typhonjs-fvtt/svelte/store/reducer': '@typhonjs-fvtt/svelte/store/reducer',
   '@typhonjs-fvtt/svelte/store/storage/web': '@typhonjs-fvtt/svelte/store/storage/web',
   '@typhonjs-fvtt/svelte/store/storage/web/plugin': '@typhonjs-fvtt/svelte/store/storage/web/plugin',
   '@typhonjs-fvtt/svelte/transition': '@typhonjs-fvtt/svelte/transition',
   '@typhonjs-fvtt/svelte/util': '@typhonjs-fvtt/svelte/util',
};
